[
    {
        "image_lastmod": 1677542547,
        "region": "North America",
        "population": "1492510",
        "descriptionFromReview": "Where cowboys and the wild west truly started, San Antonio is a beautiful and historic city with many layers to explore within and outside the city. It's a hotter town than Austin, not just in temperature, but also in terms of friendliness, activities, family values, and cultural richness (with authentic tacos of all types, Tex-Mex, Cali style, and from Mexico City), it has one of the best culinary and cocktail scenes in the country. It's one of the most affordable for millennials in the States with rich multicultural diversity, being predominantly Hispanic and inclusive. Many are bilingual in Spanish, but English is predominant as anywhere else in the States. From aviation (first military flight) to tech (the invention of the microprocessor), and even Hollywood (the first Best Picture), San Antonio has been home to many firsts. The spirit of these firsts has continued through the ages. Nowadays, there are incredibly fast internet speeds thanks to Google Fiber in many parts of town, San Antonio has all the ingredients for a booming creative economy due to a convergence of incentives in film, gaming, and traditional arts. Downtown San Antonio has old Spanish-architecture, mixed with colorful murals by local artists, and southern Texan charm, but it's the beautiful people who really make the town flourish. ",
        "slug": "san-antonio-tx-united-states",
        "short_slug": "san-antonio",
        "long_slug": "san-antonio-tx-united-states",
        "users_count": 2,
        "users_count_est": 400,
        "users_count_been": 88,
        "users_count_been_est": 17600,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/san-antonio-tx-united-states.jpg?1677542547",
        "name_chinese": "圣安东尼奥",
        "name": "San Antonio",
        "country_chinese": "美国",
        "air_quality_now": 21,
        "air_quality": null,
        "latitude": "29.4241219",
        "longitude": "-98.4936282",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "TX",
        "state_chinese": "",
        "state": "Texas",
        "internet_speed": 64,
        "air_quality_score": 5,
        "air_quality_now_score": 5,
        "humidity": "82",
        "rank": 33,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "25",
        "temperatureF": "77.338",
        "temperatureC_feels_like": 25,
        "temperatureF_feels_like": 77,
        "cost_for_nomad_in_usd": 3206,
        "cost_for_expat_in_usd": 2321,
        "cost_for_local_in_usd": 1434,
        "cost_for_family_in_usd": 5020.0990624999995,
        "total_score": 3.3785611964004034,
        "overall_score": 3.3785611964004034,
        "cost_score": 3.0502857142857143,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.420709397990675
    },
    {
        "image_lastmod": 1651968053,
        "region": "North America",
        "population": "472522",
        "descriptionFromReview": null,
        "slug": "atlanta-ga-united-states",
        "short_slug": "atlanta",
        "long_slug": "atlanta-ga-united-states",
        "users_count": 7,
        "users_count_est": 1400,
        "users_count_been": 280,
        "users_count_been_est": 56000,
        "boost": null,
        "last_2_year_growth": 49.28571428571429,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/atlanta-ga-united-states.jpg?1651968053",
        "name_chinese": "亚特兰大",
        "name": "Atlanta",
        "country_chinese": "美国",
        "air_quality_now": 56,
        "air_quality": null,
        "latitude": "33.7489954",
        "longitude": "-84.3879824",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "GA",
        "state_chinese": "",
        "state": "Georgia",
        "internet_speed": 53,
        "air_quality_score": 5,
        "air_quality_now_score": 4.291428571428572,
        "humidity": "40",
        "rank": 51,
        "weather_icon": "wi-day-sunny",
        "weather_emoji": "☀️",
        "temperatureC": "19",
        "temperatureF": "65.866",
        "temperatureC_feels_like": 19,
        "temperatureF_feels_like": 66,
        "cost_for_nomad_in_usd": 3663,
        "cost_for_expat_in_usd": 2463,
        "cost_for_local_in_usd": 1581,
        "cost_for_family_in_usd": 5532.4690625,
        "total_score": 3.3050507677766756,
        "overall_score": 3.3050507677766756,
        "cost_score": 2.528,
        "internet_score": 5,
        "leisure_quality": "4",
        "safety_level": 3.522572877936875
    },
    {
        "image_lastmod": 1645228871,
        "region": "North America",
        "population": "1317929",
        "descriptionFromReview": "The city of Dallas has captivated me to an extent that I never will find another place so memorizing to live in, with all the opportunities and amenities present.",
        "slug": "dallas-tx-united-states",
        "short_slug": "dallas",
        "long_slug": "dallas-tx-united-states",
        "users_count": 1,
        "users_count_est": 200,
        "users_count_been": 215,
        "users_count_been_est": 43000,
        "boost": null,
        "last_2_year_growth": 85.60606060606061,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/dallas-tx-united-states.jpg?1645228871",
        "name_chinese": "达拉斯",
        "name": "Dallas",
        "country_chinese": "美国",
        "air_quality_now": 25,
        "air_quality": null,
        "latitude": "32.7766642",
        "longitude": "-96.7969879",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "TX",
        "state_chinese": "",
        "state": "Texas",
        "internet_speed": 58,
        "air_quality_score": 5,
        "air_quality_now_score": 5,
        "humidity": "83",
        "rank": 76,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "20",
        "temperatureF": "68.118",
        "temperatureC_feels_like": 20,
        "temperatureF_feels_like": 68,
        "cost_for_nomad_in_usd": 3755,
        "cost_for_expat_in_usd": 2651,
        "cost_for_local_in_usd": 1593,
        "cost_for_family_in_usd": 5573.900812499999,
        "total_score": 3.235297769817174,
        "overall_score": 3.235297769817174,
        "cost_score": 2.4228571428571426,
        "internet_score": 5,
        "leisure_quality": "4",
        "safety_level": 3.6395904200617
    },
    {
        "image_lastmod": 1646352061,
        "region": "North America",
        "population": "8398748",
        "descriptionFromReview": "I've lived in New York City - Brooklyn - for over 20 years.  For visiting tourists, the best neighborhood to stay in is NOT Bushwick.  Park Slope, Prospect Heights, Ft. Green or Brooklyn Heights is preferable.  Plenty of good transportation in those areas - subway, buses or Uber.   Easy access to beaches in Long Island and New Jersey.  There's plenty to do in NYC.  Great restaurants, Broadway plays (!), and in the summer you frequently can catch a free concert.",
        "slug": "new-york-city-ny-united-states",
        "short_slug": "new-york-city",
        "long_slug": "new-york-city-ny-united-states",
        "users_count": 39,
        "users_count_est": 7800,
        "users_count_been": 2034,
        "users_count_been_est": 406800,
        "boost": null,
        "last_2_year_growth": 87.91817061361036,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/new-york-city-ny-united-states.jpg?1646352061",
        "name_chinese": "纽约市",
        "name": "New York City",
        "country_chinese": "美国",
        "air_quality_now": 44,
        "air_quality": null,
        "latitude": "40.7127837",
        "longitude": "-74.0059413",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "NY",
        "state_chinese": "",
        "state": "New York",
        "internet_speed": 48,
        "air_quality_score": 5,
        "air_quality_now_score": 4.565714285714286,
        "humidity": "31",
        "rank": 83,
        "weather_icon": "wi-day-sunny",
        "weather_emoji": "☀️",
        "temperatureC": "13",
        "temperatureF": "55.256",
        "temperatureC_feels_like": 13,
        "temperatureF_feels_like": 55,
        "cost_for_nomad_in_usd": 6292,
        "cost_for_expat_in_usd": 5030,
        "cost_for_local_in_usd": 3485,
        "cost_for_family_in_usd": 12199.0998125,
        "total_score": 3.222414914205492,
        "overall_score": 3.222414914205492,
        "cost_score": 1,
        "internet_score": 5,
        "leisure_quality": "5",
        "safety_level": 3.7336914603275
    },
    {
        "image_lastmod": 1653005014,
        "region": "North America",
        "population": "530706",
        "descriptionFromReview": "I agree with one of the previous reviews. Tucson is a great place for outdoor activities, hiking, rock climbing, etc. Yes it's hot in the summer, but monsoon rains are magnificent when they come. The cost of living is lower than a lot of other areas in the country, and as a woman I've never felt particularly unsafe. ",
        "slug": "tucson-az-united-states",
        "short_slug": "tucson",
        "long_slug": "tucson-az-united-states",
        "users_count": 6,
        "users_count_est": 1200,
        "users_count_been": 67,
        "users_count_been_est": 13400,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/tucson-az-united-states.jpg?1653005014",
        "name_chinese": "图森",
        "name": "Tucson",
        "country_chinese": "美国",
        "air_quality_now": 27,
        "air_quality": null,
        "latitude": "32.2217429",
        "longitude": "-110.926479",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "AZ",
        "state_chinese": "",
        "state": "Arizona",
        "internet_speed": 67,
        "air_quality_score": 5,
        "air_quality_now_score": 4.954285714285714,
        "humidity": "61",
        "rank": 96,
        "weather_icon": "wi-day-cloudy",
        "weather_emoji": "🌥",
        "temperatureC": "17",
        "temperatureF": "61.97",
        "temperatureC_feels_like": 18,
        "temperatureF_feels_like": 64,
        "cost_for_nomad_in_usd": 3522,
        "cost_for_expat_in_usd": 2246,
        "cost_for_local_in_usd": 1319,
        "cost_for_family_in_usd": 4615.437812499999,
        "total_score": 3.19159864544492,
        "overall_score": 3.19159864544492,
        "cost_score": 2.689142857142857,
        "internet_score": 5,
        "leisure_quality": "2",
        "safety_level": 3.3625
    },
    {
        "image_lastmod": 1662336065,
        "region": "North America",
        "population": "377165",
        "descriptionFromReview": "I have grown up in Tampa Bay and can give some quick insight.   If you want to genuinely experience the overall area or its history you'll want to visit both Ybor City and St Petersburg (First two areas that were initially settled). Clearwater is a tourist trap but has a beautiful manufactured beach (the sand as imported to make this beach what it is today).   Saint Petersburg, FL:  St Petersburg offers a few co-working spaces and at one time boasted the largest number of Kava Bars in a given city in the US (which are often used as cowork space by locals). The Brewery scene in St Petersburg is unmatched, with over 50 different breweries located in Pinellas County alone.   Nightlife: EDM/Dance Music is primarily seen in Tampa/Ybor City especially for harder genres like Dubstep/Riddim and Drum & Bass, as well as Tech House. However, St Petersburg has a reputation for being the more artistic side of the Tampa Bay area and thus has a strong community for Techno and House music.   Daytime Fun: - Kayaking through the mangroves in Lido Key (Day trip) - 'Hiking' in Weedon Island Preserve - Daytime in Ybor City (great restaurants, bars, and a bit of history) - Busch Gardens Theme Park (Excellent rollercoasters) - Art walk in St Pete - Dali Museum (St Pete) - Fort Desoto  Cons: -5 years ago Tampa Bay was extremely affordable by all accounts, but is currently pacing to become much more expensive with a 25% increase in housing costs in the last year alone and one of the highest overall inflation rates in the country. -Traveling around Tampa Bay can become expensive due to the physical size of the city and how scattered things can be. Public transit is not worth the money saved, but if you're remaining in one area, Uber is very reasonably priced.  -There are a lot of people from other cities in the US moving into Tampa Bay, so there are many people that are not a reflection of the locals here.",
        "slug": "tampa-fl-united-states",
        "short_slug": "tampa",
        "long_slug": "tampa-fl-united-states",
        "users_count": 2,
        "users_count_est": 400,
        "users_count_been": 118,
        "users_count_been_est": 23600,
        "boost": null,
        "last_2_year_growth": 39.97584541062802,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/tampa-fl-united-states.jpg?1662336065",
        "name_chinese": "坦帕",
        "name": "Tampa",
        "country_chinese": "美国",
        "air_quality_now": 40,
        "air_quality": null,
        "latitude": "27.950575",
        "longitude": "-82.4571776",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "FL",
        "state_chinese": "",
        "state": "Florida",
        "internet_speed": 59,
        "air_quality_score": 5,
        "air_quality_now_score": 4.657142857142857,
        "humidity": "59",
        "rank": 108,
        "weather_icon": "wi-day-sunny",
        "weather_emoji": "☀️",
        "temperatureC": "23",
        "temperatureF": "73.69",
        "temperatureC_feels_like": 23,
        "temperatureF_feels_like": 73,
        "cost_for_nomad_in_usd": 4026,
        "cost_for_expat_in_usd": 2516,
        "cost_for_local_in_usd": 1682,
        "cost_for_family_in_usd": 5885.792812500001,
        "total_score": 3.169242531712174,
        "overall_score": 3.169242531712174,
        "cost_score": 2.113142857142857,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.634139407483575
    },
    {
        "image_lastmod": 1669939555,
        "region": "North America",
        "population": "631490",
        "descriptionFromReview": "Great for a visit. Beautiful scenery. Good food. I thought it would be great to live here, start a startup and be in the same time zone as SF, close to Seattle, etc. But compared to Vancouver in 2009, one big change that totally ruined it for me: Absolute zombie apocalypse of drug addicts and shouting/violent home less people. It was shockingly bad. The locals often visibly carry naxalone (anti-overdose medicine, I learned) because there are so many people overdosing in the street. Police were nowhere to be seen. Such a shame, I would have loved to live in this beautiful city otherwise. ",
        "slug": "vancouver-canada",
        "short_slug": "vancouver",
        "long_slug": "vancouver-canada",
        "users_count": 14,
        "users_count_est": 2800,
        "users_count_been": 595,
        "users_count_been_est": 119000,
        "boost": null,
        "last_2_year_growth": 74.83065953654189,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/vancouver-canada.jpg?1669939555",
        "name_chinese": "温哥华",
        "name": "Vancouver",
        "country_chinese": "加拿大",
        "air_quality_now": 15,
        "air_quality": null,
        "latitude": "49.261226",
        "longitude": "-123.1139268",
        "country": "Canada",
        "country_code": "CA",
        "country_slug": "canada",
        "state_code": "",
        "state_chinese": "",
        "state": "",
        "internet_speed": 16,
        "air_quality_score": 5,
        "air_quality_now_score": 5,
        "humidity": "71",
        "rank": 109,
        "weather_icon": "wi-day-cloudy",
        "weather_emoji": "🌥",
        "temperatureC": "9",
        "temperatureF": "48.076",
        "temperatureC_feels_like": 9,
        "temperatureF_feels_like": 48,
        "cost_for_nomad_in_usd": 4038,
        "cost_for_expat_in_usd": 2787,
        "cost_for_local_in_usd": 1874,
        "cost_for_family_in_usd": 6558.890629704783,
        "total_score": 3.1668990966415587,
        "overall_score": 3.1668990966415587,
        "cost_score": 2.0994285714285716,
        "internet_score": 3.9999999999999996,
        "leisure_quality": "3",
        "safety_level": 4
    },
    {
        "image_lastmod": 1642528503,
        "region": "North America",
        "population": "947890",
        "descriptionFromReview": "All in, Austin is a good city. We live in Hill Country now so we're a bit removed. But it's beautiful area once you get away from the highways. A good tech scene. Not too expensive (~$2100 for a nice 2 bedroom apt) for the U.S. Has wineries and breweries galore. Not a great place if you are a recovering alcoholic (!). Cons: extremely hot in the summer; reaches 110 F (43.3 C) in summer afternoons from June - September. Not very diverse. Highways are loud and obnoxious. ",
        "slug": "austin-tx-united-states",
        "short_slug": "austin",
        "long_slug": "austin-tx-united-states",
        "users_count": 17,
        "users_count_est": 3400,
        "users_count_been": 581,
        "users_count_been_est": 116200,
        "boost": null,
        "last_2_year_growth": 59.408967391304344,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/austin-tx-united-states.jpg?1642528503",
        "name_chinese": "奥斯汀",
        "name": "Austin",
        "country_chinese": "美国",
        "air_quality_now": 33,
        "air_quality": null,
        "latitude": "30.267153",
        "longitude": "-97.7430608",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "TX",
        "state_chinese": "",
        "state": "Texas",
        "internet_speed": 59,
        "air_quality_score": 5,
        "air_quality_now_score": 4.817142857142857,
        "humidity": "85",
        "rank": 110,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "24",
        "temperatureF": "74.534",
        "temperatureC_feels_like": 24,
        "temperatureF_feels_like": 75,
        "cost_for_nomad_in_usd": 4436,
        "cost_for_expat_in_usd": 3388,
        "cost_for_local_in_usd": 1848,
        "cost_for_family_in_usd": 6467.327187500001,
        "total_score": 3.166259022781457,
        "overall_score": 3.166259022781457,
        "cost_score": 1.6445714285714286,
        "internet_score": 5,
        "leisure_quality": "5",
        "safety_level": 3.6476618740606
    },
    {
        "image_lastmod": 1653091416,
        "region": "North America",
        "population": "193744",
        "descriptionFromReview": "Did the previous reviewer say world class art and culture?  Where would this be because after 2 years there, I was craving art and culture.  Like, my experience is the polar opposite so unless art includes street statues that happen a month of each year and if by culture meaning you run into a single black guy on the street, I don't get it.  It's really white, very few Hispanics, almost no blacks and few Asians.  No museums (outside of historical ones).  Most of the Mormons live in Provo if that matters. There weren't really any sketchy areas I've encountered in SLC.  SLC is a good city to visit especially if you're skiing.  If you're not skiing, I don't know what else you can do.  I found the city to be quite boring.    The national parks in eastern and southern UT are gorgeous but we're talking 4-8 hour drive away. Skiing is great. I personally like Park City but it's boring there too. Dating sucks all around. Between recovering Mormons to Mormons, there aren't a lot in between even if the city attracts non-mormons to work there.  And if you're not white, it'll be a struggle in the dating scene.  SLC nightlife is dominated mainly by college kids.  There's only 3 places that I'd consider hanging at as a 30's and up nomad and they're not very close to each other.  It's a walkable city although things are a bit spread apart.    The new SLC airport did not consider those who fly on airlines other than Delta. It's a 20 minute walk to get from check in to the furthest gate in terminal B.  Imagine old folks and handicap.  Crazy.",
        "slug": "salt-lake-city-ut-united-states",
        "short_slug": "salt-lake-city",
        "long_slug": "salt-lake-city-ut-united-states",
        "users_count": 4,
        "users_count_est": 800,
        "users_count_been": 183,
        "users_count_been_est": 36600,
        "boost": null,
        "last_2_year_growth": 78.57142857142857,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/salt-lake-city-ut-united-states.jpg?1653091416",
        "name_chinese": "盐湖城",
        "name": "Salt Lake City",
        "country_chinese": "美国",
        "air_quality_now": 44,
        "air_quality": null,
        "latitude": "40.7607793",
        "longitude": "-111.8910474",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "UT",
        "state_chinese": "",
        "state": "Utah",
        "internet_speed": 61,
        "air_quality_score": 5,
        "air_quality_now_score": 4.565714285714286,
        "humidity": "50",
        "rank": 118,
        "weather_icon": "wi-day-sunny",
        "weather_emoji": "☀️",
        "temperatureC": "5",
        "temperatureF": "41.11",
        "temperatureC_feels_like": 4,
        "temperatureF_feels_like": 39,
        "cost_for_nomad_in_usd": 3354,
        "cost_for_expat_in_usd": 2167,
        "cost_for_local_in_usd": 1450,
        "cost_for_family_in_usd": 5075.2846875000005,
        "total_score": 3.1459591151325728,
        "overall_score": 3.1459591151325728,
        "cost_score": 2.8811428571428572,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.3625
    },
    {
        "image_lastmod": 1675438375,
        "region": "North America",
        "population": "2731571",
        "descriptionFromReview": "Very expensive to live in. Boring, I don't mind the weather so much but I agree with previous reviews about people here having poor social skills and making friends with the locals is VERY hard. This has been confirmed by my other expat friends from US and Europe who lived here for a bit. People overall are very serious and in a group setting things like real estate and social justice/ equality are normally main topics of the conversation. Very little culture in terms of art, museums, history etc.  Food is crazy expensive.  Summers are great because of the sunny, hot weather but the lake is cold and dirty. ",
        "slug": "toronto-canada",
        "short_slug": "toronto",
        "long_slug": "toronto-canada",
        "users_count": 21,
        "users_count_est": 4200,
        "users_count_been": 729,
        "users_count_been_est": 145800,
        "boost": null,
        "last_2_year_growth": 84.46969696969697,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/toronto-canada.jpg?1675438375",
        "name_chinese": "多伦多",
        "name": "Toronto",
        "country_chinese": "加拿大",
        "air_quality_now": 50,
        "air_quality": null,
        "latitude": "43.653226",
        "longitude": "-79.3831843",
        "country": "Canada",
        "country_code": "CA",
        "country_slug": "canada",
        "state_code": "",
        "state_chinese": "",
        "state": "",
        "internet_speed": 19,
        "air_quality_score": 5,
        "air_quality_now_score": 4.428571428571429,
        "humidity": "64",
        "rank": 127,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "7",
        "temperatureF": "44.928",
        "temperatureC_feels_like": 6,
        "temperatureF_feels_like": 43,
        "cost_for_nomad_in_usd": 4325,
        "cost_for_expat_in_usd": 3097,
        "cost_for_local_in_usd": 2012,
        "cost_for_family_in_usd": 7042.583303955663,
        "total_score": 3.121624266461194,
        "overall_score": 3.121624266461194,
        "cost_score": 1.7714285714285714,
        "internet_score": 4.863157894736842,
        "leisure_quality": "3",
        "safety_level": 3.75
    },
    {
        "image_lastmod": 1666656963,
        "region": "North America",
        "population": "634464",
        "descriptionFromReview": "The town has been taken over by tourists. Local music venues that have been around for 50+ years are closing because they can't afford the rent hikes. Tourism + out of town developers are driving prices for locals up and the job market can't keep up (minimum wage is still $7.25 an hour.) It would be possible to increase minimum wage, protect small business, and local cost of living if the state wasn't controlled by conservative republicans who won't pass any useful legislation to aid with the economic divide. But sure, let's spend  $500 million to build a brand a second football stadium. I digress.  If you do visit, please stay at a hotel instead of an Airbnb. Low-income neighborhoods are being bulldozed and gentrified by developers to build 4 story houses ideal for investment property owners seeking to rent it out as an Airbnb. (This impacts pricing for both local home buyers as well as renters.)  Last, but not least, PLEASE tip service industry workers (servers, drivers, performers, bartenders, etc.) If you can afford to visit, you can afford to tip. Thank you!",
        "slug": "nashville-tn-united-states",
        "short_slug": "nashville",
        "long_slug": "nashville-tn-united-states",
        "users_count": 1,
        "users_count_est": 200,
        "users_count_been": 167,
        "users_count_been_est": 33400,
        "boost": null,
        "last_2_year_growth": 66.00496277915633,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/nashville-tn-united-states.jpg?1666656963",
        "name_chinese": "纳什维尔",
        "name": "Nashville",
        "country_chinese": "美国",
        "air_quality_now": 55,
        "air_quality": null,
        "latitude": "36.1626638",
        "longitude": "-86.7816016",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "TN",
        "state_chinese": "",
        "state": "Tennessee",
        "internet_speed": 57,
        "air_quality_score": 5,
        "air_quality_now_score": 4.314285714285715,
        "humidity": "46",
        "rank": 150,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "19",
        "temperatureF": "65.574",
        "temperatureC_feels_like": 19,
        "temperatureF_feels_like": 66,
        "cost_for_nomad_in_usd": 4146,
        "cost_for_expat_in_usd": 2689,
        "cost_for_local_in_usd": 1360,
        "cost_for_family_in_usd": 4758.5528125,
        "total_score": 3.072201087052744,
        "overall_score": 3.072201087052744,
        "cost_score": 1.976,
        "internet_score": 5,
        "leisure_quality": "4",
        "safety_level": 3.3625
    },
    {
        "image_lastmod": 1653005355,
        "region": "North America",
        "population": "131591",
        "descriptionFromReview": null,
        "slug": "gainesville-fl-united-states",
        "short_slug": "gainesville",
        "long_slug": "gainesville-fl-united-states",
        "users_count": null,
        "users_count_est": null,
        "users_count_been": 24,
        "users_count_been_est": 4800,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/gainesville-fl-united-states.jpg?1653005355",
        "name_chinese": "盖恩斯维尔",
        "name": "Gainesville",
        "country_chinese": "美国",
        "air_quality_now": 21,
        "air_quality": null,
        "latitude": "29.651634",
        "longitude": "-82.324829",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "FL",
        "state_chinese": "",
        "state": "Florida",
        "internet_speed": 57,
        "air_quality_score": 5,
        "air_quality_now_score": 5,
        "humidity": "63",
        "rank": 151,
        "weather_icon": "wi-day-sunny",
        "weather_emoji": "☀️",
        "temperatureC": "21",
        "temperatureF": "68.916",
        "temperatureC_feels_like": 21,
        "temperatureF_feels_like": 70,
        "cost_for_nomad_in_usd": 2877,
        "cost_for_expat_in_usd": 1723,
        "cost_for_local_in_usd": 1146,
        "cost_for_family_in_usd": 4011.5034375000005,
        "total_score": 3.0670304133742485,
        "overall_score": 3.0670304133742485,
        "cost_score": 3.426285714285714,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.3625
    },
    {
        "image_lastmod": 1642723329,
        "region": "North America",
        "population": "413651",
        "descriptionFromReview": "I've been living in the Twin Cities (Saint Paul to be exact but I'm often in Mpls too) for about 8 months now. It really is a hidden gem in North America. Possibly one of the last major metropolitan areas in the US where housing is still relatively affordable if you have a good job. Lots of music venues and outdoorsy culture. It's colder than you can even imagine in the winter but that's a fun experience. Shoulder seasons are short, and summer is hot and muggy. Good food.",
        "slug": "minneapolis-mn-united-states",
        "short_slug": "minneapolis",
        "long_slug": "minneapolis-mn-united-states",
        "users_count": 1,
        "users_count_est": 200,
        "users_count_been": 114,
        "users_count_been_est": 22800,
        "boost": null,
        "last_2_year_growth": 34.02777777777778,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/minneapolis-mn-united-states.jpg?1642723329",
        "name_chinese": "明尼阿波利斯",
        "name": "Minneapolis",
        "country_chinese": "美国",
        "air_quality_now": 30,
        "air_quality": null,
        "latitude": "44.977753",
        "longitude": "-93.2650108",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "MN",
        "state_chinese": "",
        "state": "Minnesota",
        "internet_speed": 56,
        "air_quality_score": 5,
        "air_quality_now_score": 4.885714285714286,
        "humidity": "83",
        "rank": 157,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "2",
        "temperatureF": "35.93",
        "temperatureC_feels_like": 0,
        "temperatureF_feels_like": 0,
        "cost_for_nomad_in_usd": 4125,
        "cost_for_expat_in_usd": 2351,
        "cost_for_local_in_usd": 1595,
        "cost_for_family_in_usd": 5583.5065625,
        "total_score": 3.053563041909952,
        "overall_score": 3.053563041909952,
        "cost_score": 2,
        "internet_score": 5,
        "leisure_quality": "4",
        "safety_level": 3.546875
    },
    {
        "image_lastmod": 1653091426,
        "region": "North America",
        "population": "705245",
        "descriptionFromReview": "I would say the cost of living in Winnipeg is pretty accurately represented. I live here, and honestly, it's a decent cheap Canadian capital, I can live while doing my hobby here, and sharing a house. It could be a lot worse if you're thinking of coming to Canada for a while, rent can be found relatively low cost and utilities are cheap too. Meals vary, of course the locals know where the good cheap places are, I like the $5 tacos at BMC market. It is flat and very cold in the winter so do be prepared, Winnipeg is merciless that way.",
        "slug": "winnipeg-canada",
        "short_slug": "winnipeg",
        "long_slug": "winnipeg-canada",
        "users_count": 2,
        "users_count_est": 400,
        "users_count_been": 33,
        "users_count_been_est": 6600,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/winnipeg-canada.jpg?1653091426",
        "name_chinese": "温尼伯",
        "name": "Winnipeg",
        "country_chinese": "加拿大",
        "air_quality_now": 24,
        "air_quality": null,
        "latitude": "49.8997541",
        "longitude": "-97.1374937",
        "country": "Canada",
        "country_code": "CA",
        "country_slug": "canada",
        "state_code": "",
        "state_chinese": "",
        "state": "",
        "internet_speed": 16,
        "air_quality_score": 5,
        "air_quality_now_score": 5,
        "humidity": "65",
        "rank": 162,
        "weather_icon": "wi-day-cloudy",
        "weather_emoji": "🌥",
        "temperatureC": "-9",
        "temperatureF": "15.756",
        "temperatureC_feels_like": -14,
        "temperatureF_feels_like": 7,
        "cost_for_nomad_in_usd": 3144,
        "cost_for_expat_in_usd": 1902,
        "cost_for_local_in_usd": 1237,
        "cost_for_family_in_usd": 4330.771688482334,
        "total_score": 3.041373533425823,
        "overall_score": 3.041373533425823,
        "cost_score": 3.121142857142857,
        "internet_score": 3.9999999999999996,
        "leisure_quality": "3",
        "safety_level": 4.203125
    },
    {
        "image_lastmod": 1653005181,
        "region": "North America",
        "population": "118299",
        "descriptionFromReview": null,
        "slug": "beaumont-tx-united-states",
        "short_slug": "beaumont",
        "long_slug": "beaumont-tx-united-states",
        "users_count": null,
        "users_count_est": null,
        "users_count_been": 1,
        "users_count_been_est": 200,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/beaumont-tx-united-states.jpg?1653005181",
        "name_chinese": "博蒙特",
        "name": "Beaumont",
        "country_chinese": "美国",
        "air_quality_now": 34,
        "air_quality": null,
        "latitude": 30.086,
        "longitude": -94.1018,
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "TX",
        "state_chinese": null,
        "state": "TX",
        "internet_speed": 56,
        "air_quality_score": 5,
        "air_quality_now_score": 4.7942857142857145,
        "humidity": "85",
        "rank": 164,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "21",
        "temperatureF": "70.61",
        "temperatureC_feels_like": 21,
        "temperatureF_feels_like": 70,
        "cost_for_nomad_in_usd": 2717,
        "cost_for_expat_in_usd": 1741,
        "cost_for_local_in_usd": 1204,
        "cost_for_family_in_usd": 4214.539,
        "total_score": 3.0409977246141575,
        "overall_score": 3.0409977246141575,
        "cost_score": 3.609142857142857,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.4585451111462753
    },
    {
        "image_lastmod": 1678234124,
        "region": "North America",
        "population": "204759",
        "descriptionFromReview": null,
        "slug": "fayetteville-nc-united-states",
        "short_slug": "fayetteville",
        "long_slug": "fayetteville-nc-united-states",
        "users_count": null,
        "users_count_est": null,
        "users_count_been": 2,
        "users_count_been_est": 400,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/fayetteville-nc-united-states.jpg?1678234124",
        "name_chinese": "费耶特维尔",
        "name": "Fayetteville",
        "country_chinese": "美国",
        "air_quality_now": 34,
        "air_quality": null,
        "latitude": 35.053,
        "longitude": -78.8787,
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "NC",
        "state_chinese": null,
        "state": "NC",
        "internet_speed": 51,
        "air_quality_score": 5,
        "air_quality_now_score": 4.7942857142857145,
        "humidity": "48",
        "rank": 175,
        "weather_icon": "wi-day-sunny",
        "weather_emoji": "☀️",
        "temperatureC": "17",
        "temperatureF": "62.908",
        "temperatureC_feels_like": 17,
        "temperatureF_feels_like": 63,
        "cost_for_nomad_in_usd": 2758,
        "cost_for_expat_in_usd": 1855,
        "cost_for_local_in_usd": 1333,
        "cost_for_family_in_usd": 4665.4059375,
        "total_score": 3.0266484727208,
        "overall_score": 3.0266484727208,
        "cost_score": 3.5622857142857143,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.75
    },
    {
        "image_lastmod": 1675555403,
        "region": "North America",
        "population": "183823",
        "descriptionFromReview": null,
        "slug": "brownsville-tx-united-states",
        "short_slug": "brownsville",
        "long_slug": "brownsville-tx-united-states",
        "users_count": null,
        "users_count_est": null,
        "users_count_been": 3,
        "users_count_been_est": 600,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/brownsville-tx-united-states.jpg?1675555403",
        "name_chinese": "布朗斯维尔",
        "name": "Brownsville",
        "country_chinese": "美国",
        "air_quality_now": 57,
        "air_quality": null,
        "latitude": 25.914,
        "longitude": -97.4891,
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "TX",
        "state_chinese": null,
        "state": "TX",
        "internet_speed": 61,
        "air_quality_score": 5,
        "air_quality_now_score": 4.268571428571429,
        "humidity": "82",
        "rank": 181,
        "weather_icon": "wi-day-cloudy",
        "weather_emoji": "🌤",
        "temperatureC": "27",
        "temperatureF": "81.34",
        "temperatureC_feels_like": 31,
        "temperatureF_feels_like": 88,
        "cost_for_nomad_in_usd": 2714,
        "cost_for_expat_in_usd": 1621,
        "cost_for_local_in_usd": 1166,
        "cost_for_family_in_usd": 4079.4115,
        "total_score": 3.019896891483433,
        "overall_score": 3.019896891483433,
        "cost_score": 3.6125714285714285,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.65337245866625
    },
    {
        "image_lastmod": 1651536922,
        "region": "North America",
        "population": "51800",
        "descriptionFromReview": null,
        "slug": "battle-creek-mi-united-states",
        "short_slug": "battle-creek",
        "long_slug": "battle-creek-mi-united-states",
        "users_count": null,
        "users_count_est": null,
        "users_count_been": 1,
        "users_count_been_est": 200,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/battle-creek-mi-united-states.jpg?1651536922",
        "name_chinese": "巴特尔克里克",
        "name": "Battle Creek",
        "country_chinese": "美国",
        "air_quality_now": 53,
        "air_quality": null,
        "latitude": "42.3027307",
        "longitude": "-85.2850275",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "MI",
        "state_chinese": "",
        "state": "Michigan",
        "internet_speed": 70,
        "air_quality_score": 5,
        "air_quality_now_score": 4.359999999999999,
        "humidity": "63",
        "rank": 184,
        "weather_icon": "wi-day-rain",
        "weather_emoji": "🌧",
        "temperatureC": "10",
        "temperatureF": "49.574",
        "temperatureC_feels_like": 8,
        "temperatureF_feels_like": 46,
        "cost_for_nomad_in_usd": 2496,
        "cost_for_expat_in_usd": 1508,
        "cost_for_local_in_usd": 917,
        "cost_for_family_in_usd": 3210.9212500000003,
        "total_score": 3.017864941287967,
        "overall_score": 3.017864941287967,
        "cost_score": 3.8617142857142857,
        "internet_score": 5,
        "leisure_quality": "3",
        "safety_level": 3.5
    },
    {
        "image_lastmod": 1669939712,
        "region": "North America",
        "population": "55000",
        "descriptionFromReview": null,
        "slug": "grande-prairie-canada",
        "short_slug": "grande-prairie",
        "long_slug": "grande-prairie-canada",
        "users_count": null,
        "users_count_est": null,
        "users_count_been": 2,
        "users_count_been_est": 400,
        "boost": null,
        "last_2_year_growth": null,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/grande-prairie-canada.jpg?1669939712",
        "name_chinese": "大草原",
        "name": "Grande Prairie",
        "country_chinese": "加拿大",
        "air_quality_now": 16,
        "air_quality": null,
        "latitude": "55.1596768",
        "longitude": "-118.9604769",
        "country": "Canada",
        "country_code": "CA",
        "country_slug": "canada",
        "state_code": "",
        "state_chinese": "",
        "state": "",
        "internet_speed": 16,
        "air_quality_score": 5,
        "air_quality_now_score": 5,
        "humidity": "78",
        "rank": 187,
        "weather_icon": "wi-day-fog",
        "weather_emoji": "🌫",
        "temperatureC": "-0",
        "temperatureF": "31.942",
        "temperatureC_feels_like": -2,
        "temperatureF_feels_like": 28,
        "cost_for_nomad_in_usd": 2827,
        "cost_for_expat_in_usd": 1981,
        "cost_for_local_in_usd": 1399,
        "cost_for_family_in_usd": 4895.19239226842,
        "total_score": 3.015987635376463,
        "overall_score": 3.015987635376463,
        "cost_score": 3.4834285714285715,
        "internet_score": 3.9999999999999996,
        "leisure_quality": "3",
        "safety_level": 4
    },
    {
        "image_lastmod": 1667952502,
        "region": "North America",
        "population": "3990456",
        "descriptionFromReview": "I spent 4 months working here during summertime. It's one of the best summers I have ever had in my life. The city is just amazing and offers dozens of outdoor activities. There are so many different places such as parks, lakes, hills, mountains, beaches, etc. Also, you can feel the Californication vibe on every step.  I lived in Hollywood and I would avoid this place at any cost. It's just too overrated and won't meet your expectations. Hollywood (esp. West Hollywood) is a big pile of dirtiness with people wandering around. I'd suggest looking for smaller neighborhoods preferably in The Valley. That area is just lovely. Also, anything close to Santa Monica is overwhelming yet too costly.  One of the things I also didn't like was the lack of cultural influence and this is for sure not a city that will offer nice architecture. Another thing I disliked was the huge social distancing towards foreigners which is most likely part of the American culture. If you were to make deeper friendships here, this is not a place to go. You will end up getting ignored and in the worst case, people will stop any contact with you.  Also, the public transport of LA is not reliable especially if you use bus transportation. Get ready to wait a long turn before you get to a bus. I suggest either using the metro or renting a car which is probably the best option in LA. Otherwise, get prepared for long walks throughout your place of stay.  With all of the above said, I will for sure return to this city again and can't say I'm not missing it. It's one of those places where you always want to get back, at least temporarily :D",
        "slug": "los-angeles-ca-united-states",
        "short_slug": "los-angeles",
        "long_slug": "los-angeles-ca-united-states",
        "users_count": 24,
        "users_count_est": 4800,
        "users_count_been": 1217,
        "users_count_been_est": 243400,
        "boost": null,
        "last_2_year_growth": 50.12733446519524,
        "image": "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,width=600,height=300,quality=25/https://nomadlist.com/assets/img/places/los-angeles-ca-united-states.jpg?1667952502",
        "name_chinese": "洛杉矶",
        "name": "Los Angeles",
        "country_chinese": "美国",
        "air_quality_now": 52,
        "air_quality": null,
        "latitude": "34.0522342",
        "longitude": "-118.2436849",
        "country": "United States",
        "country_code": "US",
        "country_slug": "united-states",
        "state_code": "CA",
        "state_chinese": "",
        "state": "California",
        "internet_speed": 66,
        "air_quality_score": 5,
        "air_quality_now_score": 4.382857142857143,
        "humidity": "78",
        "rank": 192,
        "weather_icon": "wi-day-cloudy",
        "weather_emoji": "🌥",
        "temperatureC": "16",
        "temperatureF": "60.196",
        "temperatureC_feels_like": 16,
        "temperatureF_feels_like": 61,
        "cost_for_nomad_in_usd": 5268,
        "cost_for_expat_in_usd": 3332,
        "cost_for_local_in_usd": 2336,
        "cost_for_family_in_usd": 8175.166874999999,
        "total_score": 3.008259288969324,
        "overall_score": 3.008259288969324,
        "cost_score": 1,
        "internet_score": 5,
        "leisure_quality": "5",
        "safety_level": 3.3625
    }
]


